import = ["~/.config/alacritty/themes/themes/tokyo-night.toml"]

[font]
size = 10.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[scrolling]
history = 50000

[shell]
args = ["--login"]
program = "/usr/bin/fish"

[window]
opacity = 0.8
